---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: app-lifecycle/book-import/app-deployment
  labels:
    app: book-import
  name: book-import
  namespace: book-import
spec:
    channel: book-import/book-import-ch
    placement:
      placementRef:
        kind: PlacementRule
        name: book-import-pr

